import Vue from 'vue';
import 'vant/lib/index.css';
import { Icon } from 'vant';
import { Form } from 'vant';
import { Field } from 'vant';
import { Button } from 'vant';
import { Popup } from 'vant';
import { Tab, Tabs } from 'vant';
import { Dialog } from 'vant';
import { Picker } from 'vant';
import { Cell, CellGroup } from 'vant';
import { RadioGroup, Radio } from 'vant';
import { Tabbar, TabbarItem } from 'vant';
import { Col, Row } from 'vant';
import { Area } from 'vant';

Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Picker);
Vue.use(Dialog);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Popup);
Vue.use(Button);
Vue.use(Field);
Vue.use(Form);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Icon);
Vue.use(Col);
Vue.use(Row);
Vue.use(Area);